"""add_chapter_id_to_lessons

Revision ID: 2f1d0b37129d
Revises: 002
Create Date: 2025-10-20 22:36:53.958769+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f1d0b37129d"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("chapter_id", sa.Integer(), nullable=True))
    op.alter_column("lessons", "course_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(
        op.f("ix_lessons_chapter_id"), "lessons", ["chapter_id"], unique=False
    )
    op.create_foreign_key(None, "lessons", "chapters", ["chapter_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lessons", type_="foreignkey")
    op.drop_index(op.f("ix_lessons_chapter_id"), table_name="lessons")
    op.alter_column("lessons", "course_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("lessons", "chapter_id")
    # ### end Alembic commands ###
