"""add_teacher_position_types_table

Revision ID: ac1989ccdaba
Revises: 5a9378dbcbb6
Create Date: 2026-01-15 12:22:41.366384+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac1989ccdaba'
down_revision = '5a9378dbcbb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建教师职务类型表
    op.create_table('teacher_position_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='职务名称，如：班主任、学科教师、校长、教研室主任'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='职务代码，如：head_teacher、subject_teacher、principal'),
    sa.Column('description', sa.Text(), nullable=True, comment='职务描述'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='职务分类，如：教学类、管理类、行政类'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重，数字越小越靠前'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统预设'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_position_category_active', 'teacher_position_types', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_teacher_position_types_category'), 'teacher_position_types', ['category'], unique=False)
    op.create_index(op.f('ix_teacher_position_types_code'), 'teacher_position_types', ['code'], unique=True)
    op.create_index(op.f('ix_teacher_position_types_id'), 'teacher_position_types', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_position_types_is_active'), 'teacher_position_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_teacher_position_types_name'), 'teacher_position_types', ['name'], unique=True)
    
    # 修改teacher_teaching_assignments表，添加position_type_id字段
    op.add_column('teacher_teaching_assignments', sa.Column('position_type_id', sa.Integer(), nullable=True, comment='职务类型ID（关联TeacherPositionType）'))
    op.alter_column('teacher_teaching_assignments', 'assignment_type',
               existing_type=sa.VARCHAR(length=15),
               nullable=True,
               comment='任务类型（已废弃）：HEAD_TEACHER(班主任)/SUBJECT_TEACHER(学科教师)',
               existing_comment='任务类型：HEAD_TEACHER(班主任)/SUBJECT_TEACHER(学科教师)')
    op.create_index(op.f('ix_teacher_teaching_assignments_position_type_id'), 'teacher_teaching_assignments', ['position_type_id'], unique=False)
    op.create_foreign_key('fk_teacher_teaching_assignments_position_type_id', 'teacher_teaching_assignments', 'teacher_position_types', ['position_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除外键和索引
    op.drop_constraint('fk_teacher_teaching_assignments_position_type_id', 'teacher_teaching_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_teacher_teaching_assignments_position_type_id'), table_name='teacher_teaching_assignments')
    
    # 恢复assignment_type字段
    op.alter_column('teacher_teaching_assignments', 'assignment_type',
               existing_type=sa.VARCHAR(length=15),
               nullable=False,
               comment='任务类型：HEAD_TEACHER(班主任)/SUBJECT_TEACHER(学科教师)',
               existing_comment='任务类型（已废弃）：HEAD_TEACHER(班主任)/SUBJECT_TEACHER(学科教师)')
    op.drop_column('teacher_teaching_assignments', 'position_type_id')
    
    # 删除职务类型表
    op.drop_index(op.f('ix_teacher_position_types_name'), table_name='teacher_position_types')
    op.drop_index(op.f('ix_teacher_position_types_is_active'), table_name='teacher_position_types')
    op.drop_index(op.f('ix_teacher_position_types_id'), table_name='teacher_position_types')
    op.drop_index(op.f('ix_teacher_position_types_code'), table_name='teacher_position_types')
    op.drop_index(op.f('ix_teacher_position_types_category'), table_name='teacher_position_types')
    op.drop_index('idx_position_category_active', table_name='teacher_position_types')
    op.drop_table('teacher_position_types')
    # ### end Alembic commands ###
